name: Robot Framework CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  robot-tests:
    runs-on: windows-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Vérifier Python
        run: python --version

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Créer le dossier reports
        shell: powershell
        run: |
          if (!(Test-Path "reports")) {
            New-Item -ItemType Directory -Path "reports"
          }

      - name: Exécuter les tests Robot Framework
        run: |
          robot --outputdir reports tests/
        continue-on-error: true

      - name: Sauvegarder les rapports Robot
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-reports
          path: reports/

      - name: Échouer la pipeline si les tests ont échoué
        shell: powershell
        run: |
          if (Select-String -Path "reports\output.xml" -Pattern 'status="FAIL"') {
            Write-Host "Des tests ont échoué."
            exit 1
          } else {
            Write-Host "Tous les tests ont réussi."
          }