name: Robot Framework CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installer Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Vérifier Python
        run: python --version

      - name: Installer les dépendances Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Installer Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Installer ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver

      - name: Installer Allure
        run: |
          npm install -g allure
          allure --version

      - name: Créer les dossiers
        run: |
          mkdir -p reports
          mkdir -p allure-results

      - name: Exécuter les tests Robot Framework
        run: |
          robot --outputdir reports --listener allure_robotframework:allure-results tests/
        continue-on-error: true

      - name: Générer le rapport Allure
        if: always()
        run: |
          rm -rf allure-report
          allure generate --output allure-report allure-results

      - name: Sauvegarder les rapports Robot
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-reports
          path: reports/

      - name: Sauvegarder le rapport Allure
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/

      - name: Échouer la pipeline si les tests ont échoué
        run: |
          if grep -q 'status="FAIL"' reports/output.xml; then
            echo "Des tests ont échoué."
            exit 1
          else
            echo "Tous les tests ont réussi."
          fi